import turtle
turtle.color("red")
turtle.pensize(5)

turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.penup()
turtle.right(90)
turtle.forward(50)
turtle.pendown()
turtle.forward(50)
turtle.left(180)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(25)
